name: veegil_media
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  provider: ^6.0.3
  google_fonts: ^3.0.1
  animated_text_kit: ^4.2.2
  line_icons: ^2.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/login1.jpg
    - images/signup.jpg
